version: "3.1"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - offchain-resolver
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  backend:
    image: dm3-backend
    command: yarn workspace @dm3-org/dm3-backend start
    depends_on:
      - db
      - dm3-storage
    environment:
      REDIS_URL: redis://db:6379
      SIGNING_PUBLIC_KEY: ${SIGNING_PUBLIC_KEY}
      SIGNING_PRIVATE_KEY: ${SIGNING_PRIVATE_KEY}
      ENCRYPTION_PUBLIC_KEY: ${ENCRYPTION_PUBLIC_KEY}
      ENCRYPTION_PRIVATE_KEY: ${ENCRYPTION_PRIVATE_KEY}
      RPC: ${RPC}
      PORT: 8081
      LOG_LEVEL: 'debug'
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: redis
    restart: always

  dm3-storage:
    image: postgres:13
    restart: always
    container_name: dm3-storage
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dm3

  offchain-resolver-db:
    image: postgres
    restart: always
    container_name: offchain_resolver_db
    environment:
      POSTGRES_PASSWORD: example

  offchain-resolver:
    image: dm3-backend
    command: yarn workspace @dm3-org/dm3-offchain-resolver start
    depends_on:
      - offchain-resolver-db
    environment:
      DATABASE_URL: postgresql://postgres:example@offchain-resolver-db:5432
      PORT: 8082
      RPC: ${RPC}
      REACT_APP_ADDR_ENS_SUBDOMAIN: ${REACT_APP_ADDR_ENS_SUBDOMAIN}
      LOG_LEVEL: 'debug'

  web:
    image: dm3-backend
    command: yarn workspace @dm3-org/dm3-messenger-web start
    environment:
      REACT_APP_ADDR_ENS_SUBDOMAIN: ${REACT_APP_ADDR_ENS_SUBDOMAIN}
      REACT_APP_BACKEND: ${REACT_APP_BACKEND}
      REACT_APP_DEFAULT_DELIVERY_SERVICE: ${REACT_APP_DEFAULT_DELIVERY_SERVICE}
      REACT_APP_DEFAULT_SERVICE: ${REACT_APP_DEFAULT_SERVICE}
      REACT_APP_MAINNET_PROVIDER_RPC: ${REACT_APP_MAINNET_PROVIDER_RPC}
      REACT_APP_PROFILE_BASE_URL: ${REACT_APP_PROFILE_BASE_URL}
      REACT_APP_RESOLVER_BACKEND: ${REACT_APP_RESOLVER_BACKEND}
      REACT_APP_USER_ENS_SUBDOMAIN: ${REACT_APP_USER_ENS_SUBDOMAIN}
      REACT_APP_WALLET_CONNECT_PROJECT_ID: ${REACT_APP_WALLET_CONNECT_PROJECT_ID}
      RESOLVER_ADDR: ${RESOLVER_ADDR}

  ccip-resolver:
    image: dm3org/ccip-resolver:v0.2.7
    restart: always
    depends_on:
      - offchain-resolver
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
      LOG_LEVEL: debug
      CONFIG: |
        {
          "0x88c8cc822095cde6f92c8d20311c8e7de6a98694": {
            "type": "signing",
            "handlerUrl": "http://offchain-resolver:8082"
          }
        }
      PORT: 8181
