version: "3.1"
services:

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"

  backend:
    image: dm3-backend
    command: yarn workspace dm3-backend start
    depends_on:
      - db
    environment:
      REDIS_URL: redis://db:6379
      SIGNING_PUBLIC_KEY: ${SIGNING_PUBLIC_KEY}
      SIGNING_PRIVATE_KEY: ${SIGNING_PRIVATE_KEY}
      ENCRYPTION_PUBLIC_KEY: ${ENCRYPTION_PUBLIC_KEY}
      ENCRYPTION_PRIVATE_KEY: ${ENCRYPTION_PUBLIC_KEY}
      RPC: ${RPC}

  db:
    image: redis
    restart: always

  offchain-resolver-db:
    image: postgres
    restart: always
    container_name: offchain_resolver_db
    environment:
        POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

  offchain-resolver:
    image: dm3-backend
    command: yarn workspace dm3-offchain-resolver start
    depends_on:
      - offchain-resolver-db
    environment:
      DATABASE_URL: postgresql://postgres:example@offchain-resolver-db:5432

    ports:
      - '8082:8082'

  web:
    image: dm3-backend
    command: yarn workspace messenger-demo start
    environment:
      REACT_APP_ADDR_ENS_SUBDOMAIN: ${REACT_APP_ADDR_ENS_SUBDOMAIN}
      REACT_APP_BACKEND: ${REACT_APP_BACKEND}
      REACT_APP_DEFAULT_DELIVERY_SERVICE: ${REACT_APP_DEFAULT_DELIVERY_SERVICE}
      REACT_APP_DEFAULT_SERVICE: ${REACT_APP_DEFAULT_SERVICE}
      REACT_APP_ETHEREUM_PROVIDER: ${REACT_APP_ETHEREUM_PROVIDER}
      REACT_APP_PROFILE_BASE_URL: ${REACT_APP_PROFILE_BASE_URL}
      REACT_APP_RESOLVER_BACKEND: ${REACT_APP_RESOLVER_BACKEND}
      REACT_APP_USER_ENS_SUBDOMAIN: ${REACT_APP_USER_ENS_SUBDOMAIN}
      REACT_APP_WALLET_CONNECT_PROJECT_ID: ${REACT_APP_WALLET_CONNECT_PROJECT_ID}
      RESOLVER_ADDR: ${RESOLVER_ADDR}
    ports:
      - '${WEB_PORT}:8080'

  ccip-resolver:
    image: dm3org/ccip-resolver:v0.2.2
    restart: always
    depends_on:
      - offchain-resolver
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
      LOG_LEVEL: debug
      CONFIG: |
        {
          "0x5e0F81D5ca51D309B3A046FAeea70C4C70Df8079": {
            "type": "signing",
            "handlerUrl": "http://offchain-resolver:8081"
          }
        }
      PORT: 8181
    ports:
      - '8181:8181'
