version: '3.1'
services:
    dm3-delivery-service:
        image: dm3org/dm3-delivery-service:latest
        restart: always
        depends_on:
            - db
        environment:
            REDIS_URL: redis://db:6379
            SIGNING_PUBLIC_KEY: ${SIGNING_PUBLIC_KEY}
            SIGNING_PRIVATE_KEY: ${SIGNING_PRIVATE_KEY}
            ENCRYPTION_PUBLIC_KEY: ${ENCRYPTION_PUBLIC_KEY}
            ENCRYPTION_PRIVATE_KEY: ${ENCRYPTION_PRIVATE_KEY}
            RPC: ${RPC}
            PORT: 8083
            LOG_LEVEL: 'debug'
        volumes:
            - ./config.yml:/app/dist/config.yml
        ports:
            - '8083:8083'
    db:
        image: redis
        restart: always
