version: '3.6'

# The containers that compose the project
services:
    dm3-storage:
        image: postgres:13
        restart: always
        container_name: dm3-storage
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: dm3
