version: '3.6'

# The containers that compose the project
services:
    db:
        image: redis
        restart: always
        container_name: redis
        ports:
            - '6379:6379'
    postgres:
        image: postgres:13
        restart: always
        container_name: integration-tests-prisma
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: tests