name: Push Workflow
on: push

jobs:

    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 16.13.2
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn format:check

    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              registry-url: 'https://npm.pkg.github.com'
              node-version: 16.13.2
              cache: 'yarn'
        - name: Install
          run: yarn install
          env:
              NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
        - name: Build
          run: yarn build
        - uses: actions/upload-artifact@master
          with:
            name: lib-builds
            path: packages/lib/packages/**/dist/
        - uses: actions/upload-artifact@master
          with:
            name: lib-backend-builds
            path: packages/lib/packages/**/dist.backend/
        - uses: actions/upload-artifact@master
          with:
            name: lib-schema
            path: packages/lib/packages/**/schema/

    lib-tests:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 16.13.2
                  cache: 'yarn'
            - uses: actions/download-artifact@master
              with:
                name: lib-builds
                path: packages/lib/packages  
            - uses: actions/download-artifact@master
              with:
                name: lib-schema
                path: packages/lib/packages  
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
  
            - name: Unit Tests
              run: yarn test --ci --watchAll=false
    backend-tests:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/backend'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 16.13.2
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Build Lib
              run: |
                  cd ../lib 
                  yarn install
                  yarn build
            - name: Build
              run: yarn build
            - name: Unit Tests
              run: yarn test --ci --watchAll=false
    offchain-resolver-tests:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/offchain-resolver'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 16.13.2
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Build Lib
              run: |
                  cd ../lib 
                  yarn install
                  yarn build
            - name: Build
              run: yarn build
            - name: Unit Tests
              run: yarn test
              env: 
                  REACT_APP_USER_ENS_SUBDOMAIN: ".dev-user.dm3.eth"
                  REACT_APP_ADDR_ENS_SUBDOMAIN: ".dev-addr.dm3.eth"
                  REACT_APP_DEFAULT_DELIVERY_SERVICE: "dev-ds.dm3.eth"
