name: Push Workflow
on: push

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 18.0.0
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn format:check

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 18.0.0
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Build
              run: yarn build
            - uses: actions/upload-artifact@master
              with:
                  name: lib-builds
                  path: packages/lib/**/dist/
            - uses: actions/upload-artifact@master
              with:
                  name: lib-schema
                  path: packages/lib/**/schema/
    backend-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-backend'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    integration-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-integration-tests'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-crypto-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-crypto'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-delivery-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-delivery'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-messaging-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-messaging'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-profile-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-profile'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-shared-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-shared'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    lib-storage-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-lib-storage'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
    offchain-resolver-test:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v1
            - id: workspace-test
              uses: ./test-action
              with:
                  workspace-name: 'dm3-offchain-resolver'
                  package-pat: ${{ secrets.PACKAGE_PAT }}
