name: Push Workflow
on: push

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 18.0.0
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn format:check

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 18.0.0
                  cache: 'yarn'
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
            - name: Build
              run: yarn build
            - uses: actions/upload-artifact@master
              with:
                  name: lib-builds
                  path: packages/lib/**/dist/
            - uses: actions/upload-artifact@master
              with:
                  name: lib-backend-builds
                  path: packages/lib/**/dist.backend/
            - uses: actions/upload-artifact@master
              with:
                  name: lib-schema
                  path: packages/lib/**/schema/

    lib-tests:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: 'packages/lib'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'
                  node-version: 18.0.0
                  cache: 'yarn'
            - uses: actions/download-artifact@master
              with:
                  name: lib-builds
                  path: packages/lib
            - uses: actions/download-artifact@master
              with:
                  name: lib-schema
                  path: packages/lib
            - uses: actions/download-artifact@master
              with:
                  name: lib-backend-builds
                  path: packages/lib
            - name: Install
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

            - name: Unit Tests
              run: yarn test --ci --watchAll=false
