name: resetStagingState
on: workflow_dispatch

jobs:
    reset-staging-state:
        environment: 'staging'
        runs-on: ubuntu-latest
        steps:
            - name: Stop docker on server
              run: |
                  ssh -i ./ssh-key app@${{ vars.HOST_DOMAIN }} "\
                  cd dm3 && docker compose down"
                  ssh -i ./ssh-key root@${{ vars.HOST_DOMAIN }} "\
                  systemctl restart docker.service"
            - name: Reset state of staging environment
              run: |
                  ssh -i ./ssh-key root@${{ vars.HOST_DOMAIN }} "\
                  cd ${{ vars.PERSISTENCE_DIRECTORY }}/db && rm -r * || true; \
                  cd ${{ vars.PERSISTENCE_DIRECTORY }}/storage && rm -r * || true"
            - name: Start docker on server
              run: |
                  ssh -i ./ssh-key app@${{ vars.HOST_DOMAIN }} "\
                  cd dm3 && docker compose --env-file .env up -d && docker system prune -af"
